##################################################
# WordPress Image
##################################################

image:
  registry: docker.io
  repository: bitnami/wordpress

##################################################
# Service
##################################################

service:
  type: LoadBalancer

##################################################
# Persistence
##################################################

persistence:
  enabled: true
  size: 10Gi

##################################################
# Resources
##################################################

resources:
  requests:
    cpu: 250m
    memory: 256Mi

  limits:
    cpu: 500m
    memory: 512Mi

##################################################
# Replica Count
##################################################

replicaCount: 2

##################################################
# WordPress Credentials
##################################################

wordpressUsername: admin

##################################################
# MariaDB
##################################################

mariadb:
  auth:
    database: wordpress
